 

    
- name: Create working directory
  file:
    path: "{{ playbook_dir }}/certs"
    state: "directory"
    mode: 0755

- name: Create key pair for the server
  openssl_privatekey:
    path: "{{ playbook_dir }}/certs/server.rsa"
    size: 2048

- name: Create certificate signing request
  openssl_csr:
    common_name: "{{ common_name }}"
    country_name: "{{ country_name }}"
    email_address: "{{ email_address }}"
    locality_name: "{{ locality_name }}"
    organization_name: "{{ organization_name }}"
    path: "{{ playbook_dir }}/certs/server.csr"
    subject_alt_name: 
      - "DNS:*.{{ organization_name }}"
      - "DNS:{{ organization_name }}"
    privatekey_path: "{{ playbook_dir }}/certs/server.rsa"

 
- name: Create self-signed certificate
  openssl_certificate:
    csr_path: "{{ playbook_dir }}/certs/server.csr"
    path: "{{ playbook_dir }}/certs/server.crt"
    provider: selfsigned
    privatekey_path: "{{ playbook_dir }}/certs/server.rsa"

 
