variable "region" {}
variable "placement_tenancy" {}
variable "cluster" {}
variable "domain" {}
variable "vpc_name" {}
variable "instance_type" {}
variable "root_volume_type" {}
variable "root_volume_size" {}
variable "app_name" {}
